export type OacRecord = {
    id: number;
    estado_carga: string;
    archivo_origen: string;
    archivo_destino: string | null;
    sellado: string | null;
    confianza_global: string | null;
    campos_dudosos: string[];
    correcciones_realizadas: string[];
    notas: string[];
    tipo_orden: string | null;
    empresa: string | null;
    numero_sac: string | null;
    numero_ot: string | null;
    numero_reclamo: string | null;
    numero_oac: string | null;
    fecha: string | null;
    usuario_nombre: string | null;
    suministro_nro: string | null;
    direccion: string | null;
    barrio_villa: string | null;
    departamento: string | null;
    localidad: string | null;
    latitud: number | null;
    longitud: number | null;
    motivo_reclamo: string | null;
    descripcion_falla: string | null;
    ubicacion_falla: string | null;
    codigo_trabajo: string | null;
    tipo_instalacion: string | null;
    elementos_afectados: string | null;
    descripcion_manuscrita: string | null;
    trabajos_realizados: string | null;
    trabajos_pendientes: string | null;
    materiales_utilizados: string | null;
    apertura_puesto_medicion: string | null;
    empresa_contratista: string | null;
    operarios: string[];
    hora_inicio: string | null;
    hora_fin: string | null;
    estado_cierre: string | null;
    observaciones_cierre: string | null;
    created_at: string | null;
    updated_at: string | null;
};
